In [32]:
%matplotlib inline
import json
import pandas as pd
import numpy as np
import pprint
import time
import pytz

In [30]:
metadata1 = []
data = {}
with open('EBA.txt') as f:
    for l in f.readlines():
        x = json.loads(l)
        if "data" in x:
            data[x["series_id"]] = x["data"]
            del x["data"]
        metadata1.append(x)

In [33]:
%%time 
with open('EBA.txt') as f:
    for l in f.readlines():
        x = json.loads(l)
        if x["series_id"] != "EBA.SCL-ALL.D.H":
            continue
        pp = pprint.PrettyPrinter(indent=4)
        x["data"] = x["data"][0:10]
        pp.pprint(x)
        break

{   'data': [   ['20191016T07Z', 759],
                ['20191016T06Z', 949],
                ['20191016T05Z', 1042],
                ['20191016T04Z', 1106],
                ['20191016T03Z', 1145],
                ['20191016T02Z', 1141],
                ['20191016T01Z', 1164],
                ['20191016T00Z', 1136],
                ['20191015T23Z', 1128],
                ['20191015T22Z', 1131]],
    'description': 'Timestamps follow the ISO8601 standard '
                   '(https://en.wikipedia.org/wiki/ISO_8601). Hourly '
                   'representations are provided in Universal Time.',
    'end': '20191016T07Z',
    'f': 'H',
    'geoset_id': 'EBA.D.H',
    'last_updated': '2019-10-16T03:45:53-04:00',
    'name': 'Demand for Seattle City Light (SCL), hourly - UTC time',
    'series_id': 'EBA.SCL-ALL.D.H',
    'start': '20150701T08Z',
    'units': 'megawatthours'}
CPU times: user 2.89 s, sys: 2.17 s, total: 5.06 s
Wall time: 9.39 s

In [34]:
metadata1 = pd.DataFrame(metadata1)

In [35]:
metadata1.to_csv("metadata1.csv")

In [36]:
metadata1

,category_id,childseries,description,end,f,geoset_id,last_updated,name,notes,parent_category_id,series_id,start,units
0,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Salt River Project Agricultural Imp...,NaN,NaN,EBA.SRP-ALL.D.H,20150701T08Z,megawatthours
1,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for City of Tallahassee (TAL), hourly -...",NaN,NaN,EBA.TAL-ALL.D.H,20150701T05Z,megawatthours
2,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Tampa Electric Company (TEC), hourl...",NaN,NaN,EBA.TEC-ALL.D.H,20150701T05Z,megawatthours
3,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Tennessee Valley Authority (TVA), h...",NaN,NaN,EBA.TVA-ALL.D.H,20150701T06Z,megawatthours
4,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Associated Electric Cooperative, In...",NaN,NaN,EBA.AECI-ALL.D.H,20150701T06Z,megawatthours
5,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Los Angeles Department of Water and...,NaN,NaN,EBA.LDWP-ALL.D.H,20150701T08Z,megawatthours
6,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Louisville Gas and Electric Company...,NaN,NaN,EBA.LGEE-ALL.D.H,20150701T06Z,megawatthours
7,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Mid-Atlantic (region), hourly - UTC...",NaN,NaN,EBA.MIDA-ALL.D.H,20150701T05Z,megawatthours
8,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Midwest (region), hourly - UTC time",NaN,NaN,EBA.MIDW-ALL.D.H,20150701T06Z,megawatthours
9,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Carolinas (region), hourly - UTC time",NaN,NaN,EBA.CAR-ALL.D.H,20150701T05Z,megawatthours
10,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T00-07,HL,EBA.D.HL,2019-10-16T03:45:53-04:00,"Demand for Turlock Irrigation District (TIDC),...",NaN,NaN,EBA.TIDC-ALL.D.HL,20150701T01-07,megawatthours
11,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T01-06,HL,EBA.D.HL,2019-10-16T03:45:53-04:00,Demand for Western Area Power Administration -...,NaN,NaN,EBA.WAUW-ALL.D.HL,20151008T01-06,megawatthours
12,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T00-07,HL,EBA.D.HL,2019-10-16T03:45:53-04:00,Demand for Salt River Project Agricultural Imp...,NaN,NaN,EBA.SRP-ALL.D.HL,20150701T01-07,megawatthours
13,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T03-04,HL,EBA.D.HL,2019-10-16T03:45:53-04:00,"Demand for JEA (JEA), hourly - local time",NaN,NaN,EBA.JEA-ALL.D.HL,20150701T01-04,megawatthours
14,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T03-04,HL,EBA.D.HL,2019-10-16T03:45:53-04:00,Demand for Florida Municipal Power Pool (FMPP)...,NaN,NaN,EBA.FMPP-ALL.D.HL,20150701T01-04,megawatthours
15,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Central (region), hourly - UTC time",NaN,NaN,EBA.CENT-ALL.D.H,20150701T06Z,megawatthours
16,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Northwest (region), hourly - UTC time",NaN,NaN,EBA.NW-ALL.D.H,20150701T07Z,megawatthours
17,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for PacifiCorp West (PACW), hourly - UT...",NaN,NaN,EBA.PACW-ALL.D.H,20150701T08Z,megawatthours
18,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Public Service Company of Colorado ...,NaN,NaN,EBA.PSCO-ALL.D.H,20150701T07Z,megawatthours
19,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Puget Sound Energy, Inc. (PSEI), ho...",NaN,NaN,EBA.PSEI-ALL.D.H,20150701T08Z,megawatthours
20,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for South Carolina Electric & Gas Compa...,NaN,NaN,EBA.SCEG-ALL.D.H,20150701T05Z,megawatthours
21,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Southern Company Services, Inc. - T...",NaN,NaN,EBA.SOCO-ALL.D.H,20150701T06Z,megawatthours
22,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Arizona Public Service Company (AZP...,NaN,NaN,EBA.AZPS-ALL.D.H,20150701T08Z,megawatthours
23,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Balancing Authority of Northern Cal...,NaN,NaN,EBA.BANC-ALL.D.H,20150701T08Z,megawatthours
24,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Bonneville Power Administration (BP...,NaN,NaN,EBA.BPAT-ALL.D.H,20150701T08Z,megawatthours
25,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,Demand for Public Utility District No. 1 of Ch...,NaN,NaN,EBA.CHPD-ALL.D.H,20150701T08Z,megawatthours
26,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for New England (region), hourly - UTC ...",NaN,NaN,EBA.NE-ALL.D.H,20150701T05Z,megawatthours
27,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for New York (region), hourly - UTC time",NaN,NaN,EBA.NY-ALL.D.H,20150701T05Z,megawatthours
28,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Tennessee (region), hourly - UTC time",NaN,NaN,EBA.TEN-ALL.D.H,20150701T06Z,megawatthours
29,NaN,NaN,Timestamps follow the ISO8601 standard (https:...,20191016T07Z,H,EBA.D.H,2019-10-16T03:45:53-04:00,"Demand for Texas (region), hourly - UTC time",NaN,NaN,EBA.TEX-ALL.D.H,20150701T06Z,megawatthours
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2736,3390156,"[EBA.NWMT-ALL.NG.COL.H, EBA.NWMT-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,NorthWestern Corporation (NWMT),,3390104,NaN,NaN,NaN
2737,3390157,"[EBA.OVEC-ALL.NG.COL.H, EBA.OVEC-ALL.NG.COL.HL]",NaN,NaN,NaN,NaN,NaN,Ohio Valley Electric Corporation (OVEC),,3390104,NaN,NaN,NaN
2738,3390158,"[EBA.PJM-ALL.NG.COL.H, EBA.PJM-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,"PJM Interconnection, LLC (PJM)",,3390104,NaN,NaN,NaN
2739,3390159,"[EBA.DOPD-ALL.NG.WAT.H, EBA.DOPD-ALL.NG.WAT.HL]",NaN,NaN,NaN,NaN,NaN,PUD No. 1 of Douglas County (DOPD),,3390104,NaN,NaN,NaN
2740,3390160,"[EBA.PACE-ALL.NG.COL.H, EBA.PACE-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,PacifiCorp East (PACE),,3390104,NaN,NaN,NaN
2741,3390161,"[EBA.PACW-ALL.NG.COL.H, EBA.PACW-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,PacifiCorp West (PACW),,3390104,NaN,NaN,NaN
2742,3390162,"[EBA.PGE-ALL.NG.COL.H, EBA.PGE-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,Portland General Electric Company (PGE),,3390104,NaN,NaN,NaN
2743,3390163,"[EBA.AEC-ALL.NG.COL.H, EBA.AEC-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,PowerSouth Energy Cooperative (AEC),,3390104,NaN,NaN,NaN
2744,3390164,"[EBA.PSCO-ALL.NG.COL.H, EBA.PSCO-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,Public Service Company of Colorado (PSCO),,3390104,NaN,NaN,NaN
2745,3390165,"[EBA.PNM-ALL.NG.COL.H, EBA.PNM-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,Public Service Company of New Mexico (PNM),,3390104,NaN,NaN,NaN
2746,3390166,"[EBA.CHPD-ALL.NG.WAT.H, EBA.CHPD-ALL.NG.WAT.HL...",NaN,NaN,NaN,NaN,NaN,Public Utility District No. 1 of Chelan County...,,3390104,NaN,NaN,NaN
2747,3390167,"[EBA.GCPD-ALL.NG.WAT.H, EBA.GCPD-ALL.NG.WAT.HL]",NaN,NaN,NaN,NaN,NaN,"Public Utility District No. 2 of Grant County,...",,3390104,NaN,NaN,NaN
2748,3390168,"[EBA.PSEI-ALL.NG.COL.H, EBA.PSEI-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,"Puget Sound Energy, Inc. (PSEI)",,3390104,NaN,NaN,NaN
2749,3390169,"[EBA.SRP-ALL.NG.COL.H, EBA.SRP-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,Salt River Project Agricultural Improvement an...,,3390104,NaN,NaN,NaN
2750,3390170,"[EBA.SCL-ALL.NG.WAT.H, EBA.SCL-ALL.NG.WAT.HL]",NaN,NaN,NaN,NaN,NaN,Seattle City Light (SCL),,3390104,NaN,NaN,NaN
2751,3390171,"[EBA.SEC-ALL.NG.COL.H, EBA.SEC-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,Seminole Electric Cooperative (SEC),,3390104,NaN,NaN,NaN
2752,3390172,"[EBA.SCEG-ALL.NG.COL.H, EBA.SCEG-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,South Carolina Electric & Gas Company (SCEG),,3390104,NaN,NaN,NaN
2753,3390173,"[EBA.SC-ALL.NG.COL.H, EBA.SC-ALL.NG.COL.HL, EB...",NaN,NaN,NaN,NaN,NaN,South Carolina Public Service Authority (SC),,3390104,NaN,NaN,NaN
2754,3390174,"[EBA.SEPA-ALL.NG.WAT.H, EBA.SEPA-ALL.NG.WAT.HL]",NaN,NaN,NaN,NaN,NaN,Southeastern Power Administration (SEPA),,3390104,NaN,NaN,NaN
2755,3390175,"[EBA.SOCO-ALL.NG.COL.H, EBA.SOCO-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,"Southern Company Services, Inc. - Trans (SOCO)",,3390104,NaN,NaN,NaN
2756,3390176,"[EBA.SWPP-ALL.NG.COL.H, EBA.SWPP-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,Southwest Power Pool (SWPP),,3390104,NaN,NaN,NaN
2757,3390177,"[EBA.SPA-ALL.NG.OTH.H, EBA.SPA-ALL.NG.OTH.HL, ...",NaN,NaN,NaN,NaN,NaN,Southwestern Power Administration (SPA),,3390104,NaN,NaN,NaN
2758,3390178,"[EBA.TEC-ALL.NG.COL.H, EBA.TEC-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,Tampa Electric Company (TEC),,3390104,NaN,NaN,NaN
2759,3390179,"[EBA.TVA-ALL.NG.COL.H, EBA.TVA-ALL.NG.COL.HL, ...",NaN,NaN,NaN,NaN,NaN,Tennessee Valley Authority (TVA),,3390104,NaN,NaN,NaN
2760,3390180,"[EBA.TEPC-ALL.NG.COL.H, EBA.TEPC-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,Tucson Electric Power (TEPC),,3390104,NaN,NaN,NaN
2761,3390181,"[EBA.TIDC-ALL.NG.NG.H, EBA.TIDC-ALL.NG.NG.HL, ...",NaN,NaN,NaN,NaN,NaN,Turlock Irrigation District (TIDC),,3390104,NaN,NaN,NaN
2762,3390182,"[EBA.NSB-ALL.NG.OIL.H, EBA.NSB-ALL.NG.OIL.HL]",NaN,NaN,NaN,NaN,NaN,Utilities Commission of New Smyrna Beach (NSB),,3390104,NaN,NaN,NaN
2763,3390183,"[EBA.WALC-ALL.NG.COL.H, EBA.WALC-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,Western Area Power Administration - Desert Sou...,,3390104,NaN,NaN,NaN
2764,3390184,"[EBA.WACM-ALL.NG.COL.H, EBA.WACM-ALL.NG.COL.HL...",NaN,NaN,NaN,NaN,NaN,Western Area Power Administration - Rocky Moun...,,3390104,NaN,NaN,NaN
2765,3390185,"[EBA.WAUW-ALL.NG.WAT.H, EBA.WAUW-ALL.NG.WAT.HL]",NaN,NaN,NaN,NaN,NaN,Western Area Power Administration - Upper Grea...,,3390104,NaN,NaN,NaN

In [41]:
metadata1.name.iloc[1]

'Demand for City of Tallahassee (TAL), hourly - UTC time'

In [42]:
metadata1.name.iloc[6]

'Demand for Louisville Gas and Electric Company and Kentucky Utilities Company (LGEE), hourly - UTC time'

In [57]:
def get_series_ids(city):
    actual = metadata1[metadata1["name"].str.contains("Demand") 
                      & metadata1["name"].str.contains(city)  
                      & metadata1["name"].str.contains("local time")]
    if len(actual) != 1:
        print(actual)
        assert False
        
    predicted = metadata1[metadata1["name"].str.contains("forecast") 
                         & metadata1["name"].str.contains(city) 
                         & metadata1["name"].str.contains("local time")]
    if len(predicted) != 1:
        print(predicted)
        assert False
        
    return actual["series_id"].values[0], predicted["series_id"].values[0]

In [58]:
def extract(city_name):
    ids = get_series_ids(city_name)
    
    actual = pd.DataFrame(data[ids[0]], columns=["timestamp", "demand"])
    forecast = pd.DataFrame(data[ids[1]], columns=["timestamp", "forecast"])
    both = pd.merge(left=actual, right=forecast, left_on="timestamp", right_on="timestamp", how="outer")
    
    # already have local time, do not need timezone information
    # bit crude way to get rid of it
    both["timestamp"] = both["timestamp"].apply(lambda s: s.split("-")[0])
    both["timestamp"] = pd.to_datetime(both["timestamp"])
    both = both.set_index("timestamp").sort_index()
    
    return both

In [61]:
#city = "Portland"
city = "Tallahassee"
#city = "Los Angeles"

In [62]:
df = extract(city)
df.head(20)

                     demand  forecast
timestamp
2015-07-01 01:00:00     225     274.0
2015-07-01 02:00:00     222     255.0
2015-07-01 03:00:00     213     243.0
2015-07-01 04:00:00     206     237.0
2015-07-01 05:00:00     207     238.0
2015-07-01 06:00:00     219     252.0
2015-07-01 07:00:00     245     277.0
2015-07-01 08:00:00     266     302.0
2015-07-01 09:00:00     292     322.0
2015-07-01 10:00:00     323     347.0
2015-07-01 11:00:00     344     372.0
2015-07-01 12:00:00     376     395.0
2015-07-01 13:00:00     408     417.0
2015-07-01 14:00:00     436     436.0
2015-07-01 15:00:00     458     457.0
2015-07-01 16:00:00     474     470.0
2015-07-01 17:00:00     481     468.0
2015-07-01 18:00:00     480     461.0
2015-07-01 19:00:00     467     450.0
2015-07-01 20:00:00     444     433.0

# Check daylight savings time

In [63]:
df[(df.index>pd.to_datetime("2018-03-10 22:00:00")) & (df.index<pd.to_datetime("2018-03-11 07:00:00"))]

                     demand  forecast
timestamp
2018-03-10 23:00:00     242     241.0
2018-03-11 00:00:00     228     226.0
2018-03-11 01:00:00     219     216.0
2018-03-11 03:00:00     213     208.0
2018-03-11 04:00:00     211     201.0
2018-03-11 05:00:00     211     203.0
2018-03-11 06:00:00     215     209.0

In [64]:
df[(df.index>pd.to_datetime("2017-11-04 22:00:00")) & (df.index<pd.to_datetime("2017-11-05 07:00:00"))]

                     demand  forecast
timestamp
2017-11-04 23:00:00     277     269.0
2017-11-05 00:00:00     254     246.0
2017-11-05 01:00:00     216     231.0
2017-11-05 01:00:00     254     251.0
2017-11-05 02:00:00     233     217.0
2017-11-05 03:00:00     205     202.0
2017-11-05 04:00:00     198     195.0
2017-11-05 05:00:00     193     191.0
2017-11-05 06:00:00     192     192.0

# Re-index missing hours

In [65]:
# duplication allowed only on DST changes, check visually
df[df.index.duplicated()]

                     demand  forecast
timestamp
2015-11-01 01:00:00     255     268.0
2016-11-06 01:00:00     197     207.0
2017-11-05 01:00:00     254     251.0
2018-11-04 01:00:00     201     209.0

In [66]:
df = df[~df.index.duplicated()]

In [67]:
df = df.reindex(pd.date_range(df.index.min(), df.index.max(), freq="H"))

# Save

In [68]:
df.to_csv("{}.csv".format(city.lower()))

In [88]:
tallahassee = pd.read_csv("tallahassee.csv",index_col=0, parse_dates=True)

In [89]:
tallahassee.index

DatetimeIndex(['2015-07-01 01:00:00', '2015-07-01 02:00:00',
               '2015-07-01 03:00:00', '2015-07-01 04:00:00',
               '2015-07-01 05:00:00', '2015-07-01 06:00:00',
               '2015-07-01 07:00:00', '2015-07-01 08:00:00',
               '2015-07-01 09:00:00', '2015-07-01 10:00:00',
               ...
               '2019-10-15 18:00:00', '2019-10-15 19:00:00',
               '2019-10-15 20:00:00', '2019-10-15 21:00:00',
               '2019-10-15 22:00:00', '2019-10-15 23:00:00',
               '2019-10-16 00:00:00', '2019-10-16 01:00:00',
               '2019-10-16 02:00:00', '2019-10-16 03:00:00'],
              dtype='datetime64[ns]', length=37635, freq=None)

In [90]:
tallahassee.head()

                     demand  forecast
2015-07-01 01:00:00   225.0     274.0
2015-07-01 02:00:00   222.0     255.0
2015-07-01 03:00:00   213.0     243.0
2015-07-01 04:00:00   206.0     237.0
2015-07-01 05:00:00   207.0     238.0

In [87]:
df.index

DatetimeIndex(['2015-07-01 01:00:00', '2015-07-01 02:00:00',
               '2015-07-01 03:00:00', '2015-07-01 04:00:00',
               '2015-07-01 05:00:00', '2015-07-01 06:00:00',
               '2015-07-01 07:00:00', '2015-07-01 08:00:00',
               '2015-07-01 09:00:00', '2015-07-01 10:00:00',
               ...
               '2019-10-15 18:00:00', '2019-10-15 19:00:00',
               '2019-10-15 20:00:00', '2019-10-15 21:00:00',
               '2019-10-15 22:00:00', '2019-10-15 23:00:00',
               '2019-10-16 00:00:00', '2019-10-16 01:00:00',
               '2019-10-16 02:00:00', '2019-10-16 03:00:00'],
              dtype='datetime64[ns]', length=37635, freq='H')

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import time

import warnings
warnings.filterwarnings('ignore')

In [91]:
# load the data 
portland = pd.read_csv("portland.csv",index_col=0, parse_dates=True)
los_angeles = pd.read_csv("los angeles.csv",index_col=0, parse_dates=True)

In [92]:
portland.head()

                     demand  forecast
2015-07-22 01:00:00  1936.0       NaN
2015-07-22 02:00:00  1856.0       NaN
2015-07-22 03:00:00  1784.0       NaN
2015-07-22 04:00:00  1766.0       NaN
2015-07-22 05:00:00  1801.0       NaN

In [93]:
los_angeles.head()

                     demand  forecast
2015-07-01 01:00:00  3298.0    3475.0
2015-07-01 02:00:00  3045.0    3118.0
2015-07-01 03:00:00  2892.0    2938.0
2015-07-01 04:00:00  2787.0    2800.0
2015-07-01 05:00:00  2790.0    2743.0